
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('The Flash', 'Barry Allen is a Central City police forensic scientist with a reasonably happy life, despite the childhood trauma of a mysterious red and yellow being killing his mother and framing his father. All that changes when a massive particle accelerator accident leads to Barry being struck by lightning in his lab. Coming out of coma nine months later, Barry and his new friends at STAR labs find that he now has the ability to move at superhuman speed. <br>Furthermore, Barry learns that he is but one of many affected by that event, most of whom are using their powers for evil. Determined to make a difference, Barry dedicates his life to fighting such threats, as The Flash. While he gains allies he never expected, there are also secret forces determined to aid and manipulate him for their own agenda.', 'Running', 'https://static.episodate.com/images/tv-show/full/35624.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Game of Thrones', 'Nine noble families fight for control of the mythical land of Westeros. Political and sexual intrigue is pervasive. Robert Baratheon, King of Westeros, asks his old friend Eddard, Lord Stark, to serve as Hand of the King, or highest official. Secretly warned that the previous Hand was assassinated, Eddard accepts in order to investigate further. Meanwhile the Queens family, the Lannisters, may be hatching a plot to take power. Across the sea, the last members of the previous and deposed ruling family, the Targaryens, are also scheming to regain the throne. The friction between the houses Stark, Lannister, Baratheon and Targaryen and with the remaining great houses Greyjoy, Tully, Arryn,Tyrell and Martell leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war and political confusion, a neglected military order of misfits, the Nights Watch, is all that stands between the realms of men and icy horrors beyond.', 'Ended', 'https://static.episodate.com/images/tv-show/full/23455.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Arrow', 'Arrow is an American television series developed by writer/producers Greg Berlanti, Marc Guggenheim, and Andrew Kreisberg. It is based on the DC Comics character Green Arrow, a costumed crime-fighter created by Mort Weisinger and George Papp. It premiered in North America on The CW on October 10, 2012, with international broadcasting taking place in late 2012. Primarily filmed in Vancouver, British Columbia, Canada, the series follows billionaire playboy Oliver Queen, portrayed by Stephen Amell, who, five years after being stranded on a hostile island, returns home to fight crime and corruption as a secret vigilante whose weapon of choice is a bow and arrow. Unlike in the comic books, Queen does not go by the alias "Green Arrow". The series takes a realistic look at the Green Arrow character, as well as other characters from the DC Comics universe. Although Oliver Queen/Green Arrow had been featured in the television series Smallville from 2006 to 2011, the producers decided to start clean and find a new actor (Amell) to portray the character. Arrow focuses on the humanity of Oliver Queen, and how he was changed by time spent shipwrecked on an island. Most episodes have flashback scenes to the five years in which Oliver was missing.', 'Ended', 'https://static.episodate.com/images/tv-show/full/29560.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Lucifer', 'The Devil has come to Los Angeles…Based upon the characters created by Neil Gaiman, Sam Kieth and Mike Dringenberg for DC Entertainments Vertigo imprint, <b>Lucifer</b> is the story of the original fallen angel. Bored and unhappy as the Lord of Hell, Lucifer Morningstar has abandoned his throne and retired to L.A., where he owns Lux, an upscale nightclub.Charming, charismatic and devilishly handsome, Lucifer is enjoying his retirement, indulging in a few of his favorite things--wine, women and song–when a beautiful pop star is brutally murdered outside of Lux. For the first time in roughly 10 billion years, he feels something awaken deep within him as a result of this murder. Compassion? Sympathy? The very thought disturbs him--as well as his best friend and confidante, Mazkeen aka Maze, a fierce demon in the form of a beautiful young woman.', 'Ended', 'https://static.episodate.com/images/tv-show/full/43467.com'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Supergirl', 'Supergirl is an upcoming American television series developed by writer/producers Greg Berlanti, Ali Adler and Andrew Kreisberg set to air on CBS. It is based on the DC Comics character Supergirl (Kara Zor-El), created by Otto Binder and Al Plastino. Supergirl is a costumed superhero who is the biological cousin to Superman and one of the last surviving Kryptonians. The series was officially picked up on May 6, 2015 after receiving a series commitment in September 2014, and will debut in November 2015.<br><br>Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 12 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.

<br><br>

The costume for Supergirl was created by Colleen Atwood, who also designed the costumes for Arrow and The Flash. Benoist stated that she is aware of the costume worn by Kara in the comics books, and expressed that the micro-mini hemline of the skirt could be a little daunting but thats good. I like being pushed. Promotional photos of Benoist wearing Atwoods design were released on March 6, 2015. Atwood indicated that she wanted to embrace the past  but more importantly, thrust her into the street-style action hero of today.', 'Ended', 'https://static.episodate.com/images/tv-show/full/43234.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('DCs Legends of Tomorrow', 'When heroes alone are not enough... the world needs legends. Having seen the future, one he will desperately try to prevent from happening, time-traveling rogue Rip Hunter is tasked with assembling a disparate group of both heroes and villains to confront an unstoppable threat - one in which not only is the planet at stake, but all of time itself. Can this ragtag team defeat an immortal threat unlike anything they have ever known?', 'Ended', 'https://static.episodate.com/images/tv-show/full/46692.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('The Walking Dead', 'Rick Grimes is a former Sheriffs deputy who has been in a coma for several months after being shot while on duty. When he wakes, he discovers that the world has been taken over by zombies, and that he seems to be the only person still alive. After returning home to discover his wife and son missing, he heads for Atlanta to search for his family. Narrowly escaping death at the hands of the zombies on arrival in Atlanta, he is aided by another survivor,Glenn,who takes Rick to a camp outside the town. There,Rick finds his wife Lori and his son,Carl, along with his partner/best friend Shane and a small group of survivors who struggle to fend off the zombie hordes; as well as competing with other survivor groups who are prepared to do whatever it takes to survive.<br><br>The Walking Dead is an American horror drama television series developed by Frank Darabont. It is based on the comic book series of the same name by Robert Kirkman, Tony Moore, and Charlie Adlard. Andrew Lincoln stars as sheriffs deputy Rick Grimes, who awakens from a coma to find an apocalyptic world dominated by flesh-eating zombies, called walkers. He sets out to find his family and encounters many other survivors along the way.', 'Running', 'https://static.episodate.com/images/tv-show/full/24010.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Stranger Things', 'A love letter to the 80s classics that captivated a generation, <b>Stranger Things</b> is set in 1983 Indiana, where a young boy vanishes into thin air. As friends, family and local police search for answers, they are drawn into an extraordinary mystery involving top-secret government experiments, terrifying supernatural forces and one very strange little girl.', 'Running', 'https://static.episodate.com/images/tv-show/full/46778.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Dragon Ball Super', '<b>Dragon Ball Super</b>, a brand new television anime inspired by Akira Toriyamas Dragon Ball manga, will premiere on Fuji TV and other channels in July on Sundays at 9:00 a.m. This will be the first new Dragon Ball television series since Dragon Ball GT, which aired from 1996 to 1997.The story of the anime is set a few years after the defeat of Majin Buu, when the Earth has become peaceful once again. The voice of Goku, Gohan, and Goten, Masako Nozawa commented on the new anime, saying, 'We've always used the word 'chō' (Super) with Dragon Ball in commercials, games and the like, but the fact that the series titled Dragon Ball Super is beginning is the best thing ever.', 'Ended', 'https://static.episodate.com/images/tv-show/full/47145.'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Boku no Hero Academia', 'People are not born equal, a realization that 4-year-old Midoriya Izuku faced when bullied by his classmates who had unique special powers. Izuku was one of the rare cases where he was born with absolutely no unique powers. This did not stop Izuku from pursuing his dream, a dream of becoming a great hero like the legendary All-Might. To become the great hero he hopelessly wants to become, he now will join the ranks of one of the highest rated Hero Academies in the country: Yueiko. With the help of his idol All-Might, will he be able to claim the ranks and become a true hero?', 'Running', 'https://static.episodate.com/images/tv-show/full/52439.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('The 100', 'The series is set 97 years after a devastating nuclear war wiped out almost all life on Earth. The only known survivors are the residents of twelve space stations in Earths orbit prior to the war. The space stations banded together to form a single massive station named The Ark, where about 2,400 people live under the leadership of Chancellor Jaha. Resources are scarce and all crimes, no matter their nature or severity, are punishable by ejection into space (floating) unless the perpetrator is under 18 years of age. After the Arks life-support systems are found to be critically failing, 100 juvenile prisoners are declared expendable and sent to the surface—nearby former Washington, D.C.—in a last ditch attempt to determine if Earth is habitable again in a program called The 100, for which the show is named. The teens arrive on a seemingly pristine planet they have only seen from space. They are meant to find refuge and supplies at the old military installation, Mount Weather Emergency Operations Center, located at the Blue Ridge Mountains. However, they have landed a fair distance from it and soon face other problems. Confronting both the wonders and the dangers of this rugged new world, they struggle to form a tentative community. However, they discover not all humanity was wiped out; some people on Earth, called Grounders, survived the war, and there are even more dangers lurking Reapers (Grounders who have become cannibals) and Mountain Men (who live in Mount Weather, the original destination of the 100).', 'Ended', 'https://static.episodate.com/images/tv-show/full/33514.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Sherlock', 'Sherlock depicts consulting detective Sherlock Holmes (Benedict Cumberbatch) solving various mysteries in London. Holmes is assisted by his flatmate and friend, Dr. John Watson (Martin Freeman), who has returned from military service in Afghanistan with the Royal Army Medical Corps. Although Metropolitan Police Service Detective Inspector Greg Lestrade (Rupert Graves) and others are at first skeptical of Holmes, over time his remarkable intellect and powers of observation persuade them of his value. In part through Watsons blog documenting their adventures, Holmes becomes a reluctant celebrity with the press reporting on his cases and eccentric personal life. Both ordinary people and the British government ask for his help.

<br><br>

Although the series depicts a variety of crimes and perpetrators, Holmes conflict with archnemesis Jim Moriarty (Andrew Scott) is a recurring feature. Molly Hooper (Louise Brealey), a pathologist at St. Barts Hospital occasionally assists Holmes in his cases. Other recurring roles include Una Stubbs as Mrs Hudson, Holmes and Watsons landlady, and series co-creator Mark Gatiss as Holmes elder brother Mycroft.', 'Ended', 'https://static.episodate.com/images/tv-show/full/22410.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Supernatural', 'Supernatural is an American fantasy horror television series created by Eric Kripke. It was first broadcast on September 13, 2005, on The WB and subsequently became part of successor The CWs lineup. Starring Jared Padalecki as Sam Winchester and Jensen Ackles as Dean Winchester, the series follows the two brothers as they hunt demons, ghosts, monsters, and other supernatural beings in the world. The series is produced by Warner Bros. Television, in association with Wonderland Sound and Vision. Along with Kripke, executive producers have been McG, Robert Singer, Phil Sgriccia, Sera Gamble, Jeremy Carver, John Shiban, Ben Edlund and Adam Glass. Former executive producer and director Kim Manners died of lung cancer during production of the fourth season.<br>The series is filmed in Vancouver, British Columbia and surrounding areas and was in development for nearly ten years, as creator Kripke spent several years unsuccessfully pitching it. The pilot was viewed by an estimated 5.69 million viewers, and the ratings of the first four episodes prompted The WB to pick up the series for a full season. Originally, Kripke planned the series for three seasons but later expanded it to five. The fifth season concluded the series main storyline, and Kripke departed the series as showrunner. The series has continued on for several more seasons with Sera Gamble and Jeremy Carver assuming the role of showrunner.', 'Ended', 'https://static.episodate.com/images/tv-show/full/5348.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('The Big Bang Theory', 'Leonard and Sheldon are brilliant physicists - geniuses in the laboratory, but socially challenged everywhere else. Enter beautiful, street-smart neighbor, Penny, who aims to teach them a thing or two about life. Despite their on-again, off-again relationship in the past, Leonard believes he s found true love with Penny. Even Sheldon has found a female companion, entering into a  Relationship Agreement  with neurobiologist Amy Farrah Fowler. In their free time, Leonard and Sheldon continue to enjoy frequent trips to the comic book store and fantasy role-playing games with their ever-expanding universe of friends, including fellow scientists Koothrappali, Wolowitz and Wolowitz s adorable microbiologist wife, Bernadette.' , 'Ended', 'https://static.episodate.com/images/tv-show/full/8362.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Marvel s Agents of S.H.I.E.L.D.', 'Phil Coulson heads an elite team of fellow agents with the worldwide law-enforcement organization known as S.H.I.E.L.D. (Strategic Homeland Intervention Enforcement and Logistics Division), as they investigate strange occurrences around the globe. Its members -- each of whom brings a specialty to the group -- work with Coulson to protect those who cannot protect themselves from extraordinary and inconceivable threats.', 'Ended', 'https://static.episodate.com/images/tv-show/full/31452.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Marvel s Daredevil', 'Marvel s Daredevil, or simply Daredevil, is an American web television series created for Netflix by Drew Goddard, based on the Marvel Comics character of the same name. It is set in the Marvel Cinematic Universe (MCU), sharing continuity with the films of the franchise, and is the first in a series of shows that will lead up to a Defenders crossover miniseries. The series is produced by Marvel Television in association with ABC Studios, DeKnight Prods. and Goddard Textiles, with Steven S. DeKnight serving as showrunner on the first season, and Goddard acting as consultant. Doug Petrie and Marco Ramirez will take over as showrunners for the show s second season.

<br><br>

Charlie Cox stars as Matt Murdock / Daredevil, a lawyer-by-day who fights crime at night. The series chronicles the character s early days fighting crime, juxtaposed with the rise of crime lord Wilson Fisk, played by Vincent D Onofrio. Daredevil entered development in late 2013, a year after the film rights to the character reverted to Marvel, with Goddard initially hired in December 2013. DeKnight replaced him as showrunner and Cox was hired to star in May 2014, with Deborah Ann Woll, Elden Henson, Toby Leonard Moore, Vondie Curtis-Hall, Bob Gunton, Ayelet Zurer, and Rosario Dawson also starring. Filming takes place in New York City, in areas that still look like the old Hells Kitchen.' , 'Ended', 'https://static.episodate.com/images/tv-show/full/37444.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Vikings', 'With the promise of new land from the English, Ragnar leads his people to an uncertain fate on the shores of Wessex. King Ecbert has made many promises and it remains to be seen if he will keep them. But ever the restless wanderer, Ragnar is searching for something more and he finds it in the mythical city of Paris. Rumored to be impenetrable to outside forces, Ragnar and his band of Norsemen must come together to break down its walls and cement the Vikings legend in history.



The gripping family saga of Ragnar, Rollo, Lagertha and Bjorn continues as alliances and loyal friendships are questioned, faith is catechized and relationships are strained. VIKINGS tells the extraordinary tales of the lives and epic adventures of these warriors and portrays life in the Dark Ages, a world ruled by raiders and explorers, through the eyes of Viking society.', 'Ended', 'https://static.episodate.com/images/tv-show/full/29977.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Gotham', 'Gotham is an American crime-drama television series developed by Bruno Heller, based on characters appearing in and published by DC Comics in their Batman franchise, primarily those of James Gordon and Bruce Wayne. The series stars Ben McKenzie as the young Gordon, while Heller executive produces along with Danny Cannon, who also directed the pilot. As originally conceived, the series would have served as a straightforward story of Gordons early days on the Gotham City police force. The idea evolved not only to include the Wayne character, but also to tell the origin stories of several Batman villains. The first season order originally consisted of 16 episodes, but was later extended to 22. Gotham premiered on Fox on September 22, 2014.', 'Ended', 'https://static.episodate.com/images/tv-show/full/29671.png'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Westworld', '<b>Westworld</b> is a dark odyssey about the dawn of artificial consciousness and the evolution of sin. Set at the intersection of the near future and the reimagined past, it explores a world in which every human appetite, no matter how noble or depraved, can be indulged.', 'To Be Determined', 'https://static.episodate.com/images/tv-show/full/36210.jpg'); 

    
    INSERT INTO TvShow (title, show_description, show_status, poster)
    VALUES('Rick and Morty', 'Rick is a mentally gifted, but sociopathic and alcoholic scientist and a grandfather to Morty; an awkward, impressionable, and somewhat spineless teenage boy. Rick moves into the family home of Morty, where he immediately becomes a bad influence.', 'Running', 'https://static.episodate.com/images/tv-show/full/32157.jpg'); 

    